apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest  # Asegúrate de usar la versión que necesitas
        env:
          - name: SPARK_MODE
            value: worker
          - name: SPARK_MASTER_URL
            value: "spark://spark-master:7077"
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark-worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
